name: Approval
on: pull_request_review
jobs:
  labelWhenApproved:
    runs-on: ubuntu-latest
    steps:
      - name: approval label
      - uses: pullreminders/label-when-approved-action@master
      - env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.token }}
          ADD_LABEL: "approved"
  
